### ISSUE TITLE
Can't make uploads work: "Invalid path provided for move operation; must be a non-empty string"

### ISSUE THREAD

**Issue by lemon-juice** [symfony/psr-http-message-bridge#102]
Does the message bridge support file uploads? I don't know if I'm doing something wrong but I've stumbled upon a bug that looks like file uploads cannot possibly work due to a variable type mismatch. I've installed this library with the Slim framework where it translates Nyholm\Psr7\ServerRequest objects to Symfony\Component\HttpFoundation\Request for my controllers. In my application I use the resulting Symfony\Bridge\PsrHttpMessage\Factory\UploadedFile object to move the file to a new location:

```$uploadedFile->move($dir, $destFileName);```

And then PHP execution reaches line 64 of [UploadedFile.php](https://github.com/symfony/psr-http-message-bridge/blob/main/Factory/UploadedFile.php):

```$this->psrUploadedFile->moveTo($target);```

The problem is that the method moveTo() of the Psr\Http\Message interface requires that the $target be a string, while the bridge provides it with a File object that extends \SplFileInfo. The method returns $target, which must be a File object and it sends $target to the moveTo() psr implementation - this can't possibly work because the implementation requires a string according to the interface.

Because I had to make uploads work in my project I had no other choice than fork the library and change the above line in Factory/UploadedFile.php to:

```$this->psrUploadedFile->moveTo((string) $target);```

Please tell me what the problem is, it seems such an obvious bug with such a popular feature that I'm thinking that maybe I did something wrong. The Nyholm's library checks if the target is a string and throws an exception if it's not. But it looks like it can do that because the interface requires it to be a string.

**Comment by derrabus** [comment]
That change looks correct to me. Do you want to work on a PR?

**Comment by lemon-juice** [comment]
This is my first pull request on guthub, I hope it is fine: #103
