### ISSUE TITLE
This package does not work in symfony 6

### ISSUE THREAD

**Issue by app-lite** [symfony/psr-http-message-bridge#106]
It works in symfony 5, but in symfony 6 it fails:
`Cannot autowire argument $request of "App\Controller\HomeAction::handle()": it references interface "Psr\Http\Message\ServerRequestInterface" but no such service exists. Did you create a class that implements this interface?`

Controller code:
```
<?php

declare(strict_types=1);

namespace App\Controller;

use Laminas\Diactoros\Response\HtmlResponse;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class HomeAction
{
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return new HtmlResponse('Text');
    }
}
```
There will also be an error on ResponseInterface

**Comment by nicolas-grekas** [comment]
You might want to install `symfony/psr7-pack` to get the missing autowiring aliases.
