### ISSUE TITLE
[BC] Folder Tests is missing in v2.1.3

### ISSUE THREAD

**Issue by mykhailo-popok** [symfony/psr-http-message-bridge#108]
@nicolas-grekas  in source code (both .zip and .tar.gz) of the v2.1.3 there is no folder Tests with included files in it.

**Comment by nicolas-grekas** [comment]
You should install from source if you want the tests.

**Comment by mykhailo-popok** [comment]
we were using Tests\Fixtures\Stream and other classes as convenient methods in our tests to mock PSR behaviour
could you suggest an alternative?

**Comment by nicolas-grekas** [comment]
Install from source :)
Check https://getcomposer.org/doc/06-config.md#preferred-install

**Comment by wouterj** [comment]
Please note that classes in the `Tests` namespace are not covered by the BC promise :)

**Comment by derrabus** [comment]
> yeah installing from source takes much more time when using for all libraries

Please follow the link @nicolas-grekas posted. That document explains how you enable installing from source for a single package only.

**Comment by mykhailo-popok** [comment]
ok, I see now
thanks for advice
```
  "config": {
    "preferred-install": {
      "symfony/psr-http-message-bridge": "source",
      "*": "dist"
    },
  }
```
