### ISSUE TITLE
Reason phrase does not transfer from Symfony Response to PSR Response

### ISSUE THREAD

**Issue by mnpenner** [symfony/psr-http-message-bridge#11]
[Here's the failing test case](https://github.com/mnpenner/psr-http-message-bridge/commit/1ac133f1b92b231ba4941f0f1dd6b4e8175d8db7), for reference.

I've set the reason phrase to 'You do not have Administrator access' but the PSR response says 'Unauthorized'.

See also [Symfony #14388](https://github.com/symfony/symfony/issues/14388).

**Comment by dunglas** [comment]
See https://github.com/symfony/symfony/pull/15530#issuecomment-130995845 and https://github.com/symfony/symfony/pull/14770 for previous discussions about that.

**Comment by mnpenner** [comment]
Right. It was previously rejected for HttpFoundation, but now it's definitively incompatible with PSR7, which means that symfony/psr-http-message-bridge is forever broken unless it gets implemented. I see that you [mentioned](https://github.com/symfony/symfony/pull/14770#issuecomment-106393332) that already though.

Technically, you *can* "fix" psr-http-message-bridge with a [hack](http://stackoverflow.com/a/3475714/65387), but it's not ideal.

**Comment by stof** [comment]
@mnpenner such hack would be very fragile, because it will never be covered by any BC promise (private stuff are entirely internal).

**Comment by xabbuh** [comment]
@stof Well, strictly taken we have to keep the property as it is protected and not private.

**Comment by fabpot** [comment]
Closing for the same reasons I already mentioned in the other tickets, one should not rely on the HTTP status text.
