### ISSUE TITLE
does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by precamp-io** [symfony/psr-http-message-bridge#116]
Class Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver located in C:/xxxx/vendor/symfony/psr-http-message-bridge\ArgumentValueResolver (1)\PsrServerRequestResolver.php does not comply with psr-4 autoloading standard. Skipping.

Can you advice how I can correct this?

**Comment by derrabus** [comment]
Please go to https://github.com/symfony/symfony/discussions for support questions.
