### ISSUE TITLE
Support `Request::$requestFactory`

### ISSUE THREAD

**Issue by KorvinSzanto** [symfony/psr-http-message-bridge#12]
We currently use the `new` keyword to construct a symfony request instance causing this bridge to ignore the `Request::$requestFactory` static property. Can we use the `Request::create` method instead so that we can support custom request subclasses?

**Comment by KorvinSzanto** [comment]
I've added a PR that fixes the tests and adds this feature.

**Comment by KorvinSzanto** [comment]
@dunglas What about changing all of the private properties and methods in HttpFoundationFactory to protected to make extending this class easier? Is there any reason they are currently private?

**Comment by dunglas** [comment]
Protected properties and methods make the maintenance harder (such properties and methods become covered by the BC promise). We usually create new extension points (switch something private to protected) only with a good use case.

But it's why I was suggesting to add a protected property with the name of the class (and then use this this variable to dynamically instantiate the request object) in this comment https://github.com/symfony/psr-http-message-bridge/pull/13#issuecomment-152616396

**Comment by KorvinSzanto** [comment]
Thanks for the feedback on this @dunglas!
