### ISSUE TITLE
Rewind() Stream body while creating Psr7 Response/Request

### ISSUE THREAD

**Issue by danieledangeli** [symfony/psr-http-message-bridge#17]
I was using this bridge to translate a SF Response into a Psr7 Response.
While doing that I've realised that:
- once created a request if you call $psr7Response->getBody()->getContents() it has an "empty" body.

If you call instead:
$psr7Response->getBody()->rewind() //seek the cursor at the beginning of the stream
$psr7Response->getBody()->getContents() 

it works.

Should the rewind() be a responsability of DiactorosFactory instead of a "consumer" one?

**Comment by stof** [comment]
``getContents`` is indeed documented as returning the remaining content in PSR-7, not the whole content. So this is a bug in the converter

**Comment by stof** [comment]
Closing this as rewinding is necessary with PSR-7 to get the whole content (or you should use ``__toString`` instead)

**Comment by danieledangeli** [comment]
@stof exactly what I meant.

"...is indeed documented as returning the remaining content in PSR-7"
Why I should receive the an empty body even if I never "consumed" that stream? If I'm creating with a factory a new response object (from a SF  one that I never read)  I would expect to have a body "ready to read" and not a stream and the end of the file.

For instance, let's consider we're inside a behat test who is using the KernelDriver

 $response = $this->getClient()->getResponse(); //the SF response I never called getContent()
 $psr7FactoryReq = new DiactorosFactory();
 $psrResponse = $psr7FactoryResp->createResponse($response);
 $psr7Response->getBody()->getContents() it will return an empty body.

**Comment by stof** [comment]
@danieledangeli writing to a stream let the cursor at the end of the written content. You cannot assume that the cursor is at the beginning. this is not how streams are working

**Comment by stof** [comment]
And your sentence ``it will return an empty body.`` is wrong. ``->getBody()->getContents()`` **does not** return the body. It returns part of it. If you want to get the full data of the body, you should either use ``__toString`` or ensure that the stream is rewound before reading it. This is exactly what PSR-7 defines

**Comment by danieledangeli** [comment]
Ok, that's fine!
I was thinking in a "read only" use case.
If you have to manipulate the body of the request that make sense.
Tks!
