### ISSUE TITLE
Zend Diactoros must be installed to use the DiactorosFactory.

### ISSUE THREAD

**Issue by jbenoit2011** [symfony/psr-http-message-bridge#20]
I just run `composer require --dev symfony/psr-http-message-bridge` and the following error is triggered in the early stages of request handling :
`Zend Diactoros must be installed to use the DiactorosFactory.`
Here is the full stack trace given by Sf error page : https://gist.github.com/jbenoit2011/0e84a48344d6bfe2b98d

Thank you.

Let me know if you need more details.

**Comment by stof** [comment]
@jbenoit2011 SensioFrameworkExtraBundle needs to be able to convert requests and responses bot ways (actually requests one way and responses the other way). This bridge considers the zend-diactoros dependency as optional as you may not need this way of the conversion (for PSR-7 to HttpFoundation, you don't need zend-diactoros to be installed). So you need to install ``zendframework/zend-diactoros`` too.

Btw, you probably want to register it as an actual requirement rather than a dev requirement. you probably need the bridge in prod too, not only during development (``require-dev`` is best suited for development-only dependencies, like deps used only inside the testsuite or in developer tools like class generators)

**Comment by jbenoit2011** [comment]
@stof Actually, we use the bridge only in our Behat tests. So `require-dev` is correct.
Do you think it can be fixed by moving `zendframework/zend-diactoros` from `suggest` to `require` section in `composer.json`?

**Comment by stof** [comment]
> Do you think it can be fixed by moving zendframework/zend-diactoros from suggest to require section in composer.json?

No, because other usages of the bridge are possible without zend-diactoros (when you only need the HttpFoundationFactory). zendframework/zend-diactoros is an optional dependency

**Comment by jbenoit2011** [comment]
Maybe I find out why this error is triggered.

We have `sensio/framework-extra-bundle` as a dependency.
In the file [psr7.xml](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v3.0.14/Resources/config/psr7.xml), service `sensio_framework_extra.psr7.http_message_factory` is declared with `class="Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory"`. This service is injected into `sensio_framework_extra.psr7.converter.server_request`.

But since,  `zendframework/zend-diactoros` is not mandatory and [an exception is thrown](https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/DiactorosFactory.php#L36) in the constructor of this class, there are chances this service cannot be instantiated at bootstrap.

How can we modify the dependency to `zendframework/zend-diactoros`?

**Comment by stof** [comment]
@jbenoit2011 well, you have 2 solutions:

- if you need the PSR-7 conversion in SensioFrameworkExtraBundle, add the ``zendframework/zend-diactoros`` package to your dependencies, alongside the bridge
- if you don't need it, disable it in the bundle config:

  ```yaml
  sensio_framework_extra:
      psr_message: false
  ```

**Comment by jbenoit2011** [comment]
I actually do not need PSR-7 conversion in SensioFrameworkExtraBundle. So I will disable it, as you suggest me.
But these are workarounds, maybe should we find a solution or at least leave a note somewhere?
Because in the case, you need PSR-7 conversion in SensioFrameworkExtraBundle, the `zendframework/zend-diactoros` should be in `require` section, since it is used in services declaration, in `psr7.xml`.

**Comment by stof** [comment]
@jbenoit2011 but this is the same for SensioFrameworkExtraBundle: this feature is an optional feature of the bundle. So it cannot always require this dependency (most people using the bundle won't actually use PSR-7 requests and responses in their controllers but Symfony ones, as they would be following the Symfony doc)

**Comment by stof** [comment]
@jbenoit2011 the bundle auto-detects whether it should enable the PSR-7 conversion layer automatically or no (by changing the default value of the config). I sent a PR to improve this logic.

**Comment by jbenoit2011** [comment]
Thank you for the fix and for your patience.
I leave you close the ticket, if you think it is necessary.

**Comment by fabpot** [comment]
Fixed in SensioFrameworkExtraBundle
