### ISSUE TITLE
Question: Is this project dead?  Hardly any forks or stars

### ISSUE THREAD

**Issue by rparsi** [symfony/psr-http-message-bridge#21]
What symfony components can be used to implement PSR-7?

**Comment by weaverryan** [comment]
@rparsi This project is definitely not dead - there are commits on it just last month :).

But I don't understand your question. This bridge allows you to convert to and from Symfony's Request and Response objects to a PSR-7 implementation.

**Comment by rparsi** [comment]
@weaverryan I'm doing research on PSR-7 for a new project at work, thought this was a Symfony component to implement PSR-7 in a non-symfony application.  Later I found out that Silex already provides middleware features. So just a case of me being a noob, got confused as to what this repo is for.

**Comment by weaverryan** [comment]
@rparsi no worries :)
