### ISSUE TITLE
Can not change URI

### ISSUE THREAD

**Issue by thierryve** [symfony/psr-http-message-bridge#29]
Hi,

First of all, great library!

I tried to modify the URI path in psr 7 request and after that create a symfony request

```
$uri = $psr7Request->getUri()->withPath('/url');
$psr7Request = $psr7Request->withUri($uri);
```

When i use the HttpFoundationFactory the return object contains the initial url not the expected url(/url).
the problem is with array_replace i assume.

```
$server = array_replace($server, $psrRequest->getServerParams());
```

If you change the order of the parameters the uri is overwritten.

Thank you in advance

**Comment by nicolas-grekas** [comment]
PR welcome if anyone needs this fix and would like to have a look.

**Comment by nicolas-grekas** [comment]
This staled, closing.
