### ISSUE TITLE
[Discuss] Support body streaming

### ISSUE THREAD

**Issue by csarrazi** [symfony/psr-http-message-bridge#3]
As mentioned in the blog post, large bodies are not handled yet.

As a means to solve this issue, the body should be streamed.

For converting a PSR-7 body (which should be a stream), would an approach like https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/HttpFoundation/StreamResponse.php be valid here? (or provide a callback for a `StreamedResponse` object)

Converting an HttpFoundation's `StreamedResponse` could be done using an object implementing PSR-7's `StreamInterface`, injected in a PSR-7 response (from Diactoros, for example).

**Comment by dunglas** [comment]
As discussed on Twitter, I think the cleaner way would be to add resource support directly in HttpFoundation.

**Comment by csarrazi** [comment]
True. However this means that the approach will only be compatible with Symfony 2.8 and onwards, as this means that we need to make sure that the body is either a stream, or a string.

Regardless, I'll add an issue in symfony/symfony (if there's not already one), and provide a PR soon, for this.

**Comment by andig** [comment]
Could you kindly provide an update in how far `StreamedResponse` is compatible with the PSR message bridge?

**Comment by hectorj** [comment]
Hi!

Is this still being considered?

**Comment by stof** [comment]
Well, nobody contributed to this bridge to have the feature. So for now the state is the same: it is only a suggestion here.

**Comment by andig** [comment]
@stof what is the current status? Doesn't https://github.com/symfony/symfony/issues/24437 and https://github.com/symfony/http-foundation/commit/1b2736dc9bec4dc031b069211b2f1bd8afe15b18 and https://github.com/symfony/psr-http-message-bridge/blob/66085f246d3893cbdbcec5f5ad15ac60546cf0de/Factory/DiactorosFactory.php#L130 mean that this is actually implemented?

**Comment by hectorj** [comment]
@andig if I understood this ticket correctly, it's about the doing it other way: creating a Symfony `StreamedResponse` from a PSR7 Response (while what you're pointing at is creating a PSR7 Response from a Symfony `StreamedResponse`)

**Comment by stof** [comment]
@andig the code in the bridge here is copying all the StreamedResponse body in the PSR-7 request at the time of doing the conversion. While the way being used avoids loading everything in memory AFAICT, this still makes streaming twice:
- once from the SF response to the PSR-7 one
- once from the PSR-7 one to the client

What this issue is suggesting is to have a special kind of PSR-7 Stream which would reference the HTTPFoundation StreamedResponse internally, to delay the sending (but I'm not sure this is easily done though)

**Comment by danizord** [comment]
Just opened a PR to implement it - https://github.com/symfony/psr-http-message-bridge/pull/50.
