### ISSUE TITLE
Version of symfony/http-foundation is too strict?

### ISSUE THREAD

**Issue by leroy0211** [symfony/psr-http-message-bridge#33]
I guess the required composer version of `symfony/http-foundation` is too strict, because installation is restricted to the Minor version of 3.0 and 4.0. Any other minor installation of `symfony/http-foundation` like `3.1`, `3.2`, etc. is not allowed.

**Comment by fabpot** [comment]
What makes you think so? `~2.3|~3.0|~4.0` means 2.3 or 2.x where x > 3. The same goes for 3.0 and 4.0. It allows 3.x and 4.x where x = 0.

**Comment by leroy0211** [comment]
Well, I had problems installing this in a project. 

But I guess my understanding of semver is still not complete. I thought that `~3.0` meant everything between 3.0 and 3.0.x. My misunderstanding.
