### ISSUE TITLE
this package no support symfony4

### ISSUE THREAD

**Issue by saintho** [symfony/psr-http-message-bridge#37]
this package no support symfony4, Is there any plan to support it?

**Comment by xabbuh** [comment]
@saintho Would you like to create a PR that updates the version constraints?

**Comment by kejwmen** [comment]
@xabbuh looks like it needs to be tagged, #32 is merged.

**Comment by kiler129** [comment]
@dunglas Can you tag to allow installation in stable env?

**Comment by dunglas** [comment]
@kiler129, only @fabpot can tag (ping).

**Comment by fabpot** [comment]
v1.0.1 is tagged now.
