### ISSUE TITLE
Using with Symfony 4.1 produces deprecations: UploadedFile::getClientSize" is deprecated

### ISSUE THREAD

**Issue by Adapik** [symfony/psr-http-message-bridge#41]
Method `DiactorosFactory::createUploadedFile` uses method `Symfony\Component\HttpFoundation\File\UploadedFile::getClientSize` but now this method is deprecated

Notice from phpunit-bridge:

`"Symfony\Component\HttpFoundation\File\UploadedFile::getClientSize" is deprecated since Symfony 4.1. Use getSize() instead.`

**Comment by Nyholm** [comment]
Fixed in #45

**Comment by Nyholm** [comment]
This issue is fixed in master. This can be closed.
Thank you for reporting this.
