### ISSUE TITLE
Nulls transformed to UploadedFile with UPLOAD_ERR_NO_FILE

### ISSUE THREAD

**Issue by szymach** [symfony/psr-http-message-bridge#49]
Hello,

I have a question regarding [this](https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/DiactorosFactory.php#L92) bit of code. 

Context: I have a form with an optional file field and I transform the `ServerRequestInterface` object back into a `Symfony\Component\HttpFoundation\Request` in order to handle the submit through the `handleRequest` method. 

Issue: Since the file field is optional, there can be a `null` value sent for it. The code linked above transforms it into an `UploadedFile` instance with the error `UPLOAD_ERR_NO_FILE`, which in turn is validated by the Symfony file validator and there is a violation raised, that no file has been sent.

Question: Is there a way around this? So far I have resorted to manual filtering out of objects with that specific error, but I would rather opt for a more elegant solution.

**Comment by stof** [comment]
The code you are linking to is about converting a HttpFoundation Request into a ServerRequestInterface, so it is not used in the workflow you describe.

**Comment by szymach** [comment]
Indeed, it was not, but that is not the real issue here, it is just a consequence of how `null` is handled for files. I am not sure creating an instance of uploaded file with an error code in all cases is the proper way to go, since a file may be optional. On the other hand, I do not know if there is a way to distinguish such a case. For my project I was able to get my hands on a custom form handler for PSR7 request and filter out such empty file objects there. So there's 3 options:

1. Do nothing.
2. Do not treat `null` as a non-uploaded file.
3. Perhaps add a form handler for PSR-7?

**Comment by nicolas-grekas** [comment]
DiactorosFactory is now deprecated but I suppose this would apply to PsrHttpFactory?
PR welcome is anyone needs this to be fixed.

**Comment by szymach** [comment]
Hey, I will try to take a look at how it is handled in the PsrHttpFactory and see whether it could use fixing. Thing is, I am not sure if my issue is specific to my use case and if there is anything that actually should be fixed.

**Comment by nicolas-grekas** [comment]
Please reopen if you still have the issue.
