### ISSUE TITLE
Support "any" PSR-7 implementation

### ISSUE THREAD

**Issue by sagikazarmark** [symfony/psr-http-message-bridge#5]
Currently only one implementation is supported out-of-the-box: diactoros. One more major implementation which should also be supported: guzzle/psr7

To make sure that a PSR-7 implementation is installed, the virtual package could be required:
https://github.com/php-http/discovery/

https://packagist.org/providers/psr/http-message-implementation

Last, but not least: it would be awesome to have a discovery layer which allows to use any PSR-7 implementation without the knowledge which is actually used. See the concept here:

https://github.com/php-http/discovery/

The installed implementation is detected and the appropriate factory is instantiated.

**Comment by dunglas** [comment]
`psr/http-message-implementation` can be added to the `suggest` section but must not be added in the `require` section of `composer.json`: an implementation is not necessary for transforming PSR-7 message s to HttpFoundation messages.

About `php-http/discovery`, it looks to me like duplicated (but more generic) work. The bridge is designed to work with any implementation (in both ways) thanks to the factory system. At the end, `php-http/discovery` must know PSR-7 implementation internals.
I would prefer having a `GuzzleFactory` directly inside this bridge than depending of an external layer.

**Comment by sagikazarmark** [comment]
> it looks to me like duplicated (but more generic) work

No duplication here, the purpose is different. You can create PSR-7 Messages from generic data.

> I would prefer having a GuzzleFactory directly inside this bridge than depending of an external layer.

There is a misunderstanding here: I never suggested using an external library. Actually, what I tried to show is the discovery layer where there is a possibility that you are not aware of the installed PSR-7 implementation when you configure your application. So that the factory is automatically found for you.

**Comment by sagikazarmark** [comment]
> an implementation is not necessary for transforming PSR-7 message s to HttpFoundation messages

Fair enough

**Comment by dunglas** [comment]
I fail to understand how this "discovery layer" works. It relies on `php-http/discovery` right? And this library is not fundamentally different than the bridge. The bridge can already work with any installed PSR-7 implementation if a corresponding factory exist.

**Comment by sagikazarmark** [comment]
The discovery package was created to allow HTTP Clients to rely on any installed PSR-7 implementation with zero-config. Since the client itself does not rely on a specific implementation (as neither this bridge does) you have two options:

1. You make a requirement that the chosen factory is passed when the application is configured (DI)

or

2. You doesn't require it (though you can allow as an optional argument) and try to detect (based on available classes or anything else) This way you don't have to configure it every time. This is especially useful when you need an implementation in code which is not the application itself, but a reusable package (like this one)

You can see the discovery layer working [here](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/ProxyClient/AbstractProxyClient.php#L64)

**Comment by Nyholm** [comment]
:+1: For this. Will you consider reviewing it if I send a PR?

**Comment by sagikazarmark** [comment]
Well, our concept changed a lot regarding discovery in the past. I highly doubt that this package wants to rely on Puli. However, our message factory concept might still be interesting here.

**Comment by Nyholm** [comment]
Yeah. No discovery but the message factory. I would like to do something like this:

```php
public function proxyAction(Request $symfonyRequest, $token)
    {
        // Some validation
        // ..

         // Use the Symfony PSR7 bridge to convert a symfony request to PSR7
        $psr7Factory = new Psr7Factory($this->get('httplug.message_factory'));
        $psrRequest = $psr7Factory->createRequest($symfonyRequest);
        
        // Change url
        $psrRequest = $psrRequest->withUri($this->get('httplug.uri_factory')->createUri('http://www.example.com'));

        // send request
        $psrResponse = $this->get('httplug.client')->sendRequest($psrRequest);

        // Convert a PSR7 response to Symfony response
        $httpFoundationFactory = new HttpFoundationFactory();
        $symfonyResponse = $httpFoundationFactory->createResponse($psrResponse);

        return $symfonyResponse;
    }
```

**Comment by mindplay-dk** [comment]
With [PSR-17](https://github.com/php-fig/fig-standards/tree/master/proposed/http-factory) we should eventually be able to abstract from a specific implementation by using factories.
