### ISSUE TITLE
Compatibility with `"zendframework/zend-diactoros": "^2.0.0"`

### ISSUE THREAD

**Issue by zerkms** [symfony/psr-http-message-bridge#51]
At the moment `Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory::createRequest` refers to the `Zend\Diactoros\ServerRequestFactory::normalizeServer` which was removed in the `v2.0.0`, so it throws `Call to undefined method Zend\Diactoros\ServerRequestFactory::normalizeServer()`

**Comment by uphlewis** [comment]
This PR provides a backwards-compatible fix:
https://github.com/symfony/psr-http-message-bridge/pull/54
