### ISSUE TITLE
Consider adding a `.gitatttributes` file with an `export-ignore` entry for `Tests`.

### ISSUE THREAD

**Issue by Jaesin** [symfony/psr-http-message-bridge#56]
Something like:

```
# Ignore from prefer-dist install
Tests                                export-ignore

```
See: https://git-scm.com/docs/gitattributes#_creating_an_archive

**Comment by fabpot** [comment]
Thanks for the suggestion. That's a topic we've talked about numerous times in the past for the Symfony framework and some other projects I manage (like Twig). It was always rejected. So, I'm going to close this one.

**Comment by Jaesin** [comment]
I see. Ref: <https://github.com/symfony/symfony/issues/6605>.
