### ISSUE TITLE
Added psr/http-message-implementation to composer.json without PR

### ISSUE THREAD

**Issue by dunglas** [symfony/psr-http-message-bridge#6]
My bad. I used the inline GitHub editor and I forgot to check the "in your fork" option... d7660b8e47b08853f652a4b196031d318b487671
But this commit partially fixes #5.

Should I revert it or can I leave it as-is?

**Comment by weaverryan** [comment]
I personally don't think it's an issue - I'd say leave it, and I'm sure we'll use PR's in the future just fine :).

**Comment by xabbuh** [comment]
Yeah, I think that change does not need to be discussed. So I would be fine with keep it as is too.

**Comment by xabbuh** [comment]
Now that I see this change: Shouldn't we actually do a better job and provide a more convenient exception in `HttpFoundationFactory` in case the PSR HTTP message interface cannot be found?

**Comment by dunglas** [comment]
@xabbuh yes it would be a nice addition.

**Comment by xabbuh** [comment]
Never mind, the implementation is passed as an argument to the factory. So there is nothing that needs to be checked inside it.
