### ISSUE TITLE
PsrHttpFactory assumes parsed Symfony Request body, results in invalid getParsedBody

### ISSUE THREAD

**Issue by crtl** [symfony/psr-http-message-bridge#73]
When creating a psr request from symfony request the [`Symfony\Bridge\PsrHttpMessage\FactoryPsrHttpFacory`](https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/PsrHttpFactory.php) just assumes the symfony request is already parsed ([Line 68](https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/PsrHttpFactory.php#L68)).
When you call `Psr\Http\Message\ServerRequestInterface::getParsedBody()` on the returned request it will return an empty array, if the body was not properly parsed in symfony before.

Ive created a small helper class following the example of the documentation using nyholms psr implementation:

```php
<?php

use Nyholm\Psr7\Factory\Psr17Factory;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory;
use Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class RequestResponseFactory
{

    /**
     * @var Psr17Factory
     */
    protected $psrFactory;

    /**
     * @var PsrHttpFactory
     */
    protected $psrHttpFactory;

    /**
     * @var HttpFoundationFactoryInterface
     */
    protected $httpFoundationFactory;

    public function __construct()
    {
        $this->psrFactory = new Psr17Factory();
        $this->psrHttpFactory = new PsrHttpFactory($this->psrFactory, $this->psrFactory, $this->psrFactory, $this->psrFactory);
        $this->httpFoundationFactory = new HttpFoundationFactory();
    }

    public function responseFromFoundation(Response $response): ResponseInterface {
        return $this->psrHttpFactory->createResponse($response);
    }

    public function responseFromPsr(ResponseInterface $response): Response{
        return $this->httpFoundationFactory->createResponse($response);
    }

    public function requestFromFoundation(Request $request) {
        return $this->psrHttpFactory->createRequest($request);
    }

    public function requestFromPsr(ServerRequestInterface $request) {
        return $this->httpFoundationFactory->createRequest($request);
    }

}
```

In the controller it is called like this:

```php
use Nyholm\Psr7\Response as Psr7Response;
use Symfony\Component\HttpFoundation\Request

class TestController {


  public function index(Request $request, RequestResponseFactory $requestResponseFactory) {
     $psrRequest = $requestResponseFactory->requestFromFoundation($request);
     var_dump($psrRequest->getParsedBody());
  }

}
```

When sending a json request to that controller it will dump an empty array:

```curl

curl --request POST \
  --url http://localhost/ \
  --header 'content-type: application/json' \
  --data '{
  "foo": "bar"
}'

```

**Comment by vhenzl** [comment]
A possible solution is to install [`symfony-bundles/json-request-bundle`](https://packagist.org/packages/symfony-bundles/json-request-bundle) or [qandidate/symfony-json-request-transformer](https://packagist.org/packages/qandidate/symfony-json-request-transformer) package. It will add request listener which parsers JSON requests and polulates `Request::request` bag automatically. Then this bridge will work as expected.

**Comment by nicolas-grekas** [comment]
I don't think there is anything to do in the bridge on this topic.
Closing therefor.
Please submit a PR if you think we should reconsider.
