### ISSUE TITLE
Support cycle

### ISSUE THREAD

**Issue by catch56** [symfony/psr-http-message-bridge#76]
The message bridge (and also Symfony Contracts) don't follow the same version numbers as other Symfony components, which is reasonable for brand new components that might change on a different schedule.

However, I'm not clear what this means for the frequency of major and minor releases, and EOL for old major and minor releases. Apologies if this is already clarified elsewhere, I was unable to find it in the usual places.

**Comment by nicolas-grekas** [comment]
new "features" in Symfony Contracts are released in sync with regular releases of Symfony components. Bug fixes on the go.
For this repo, it's on the go also.
