### ISSUE TITLE
Test failure with `zendframework/zend-diactoros` installed

### ISSUE THREAD

**Issue by siwinski** [symfony/psr-http-message-bridge#8]
> PHPUnit 4.7.4 by Sebastian Bergmann and contributors.
>
> F.........
>
> Time: 161 ms, Memory: 6.25Mb
>
> There was 1 failure:
>
> 1) Symfony\Bridge\PsrHttpMessage\Tests\Factory\DiactorosFactoryTest::testCreateRequest
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'Content'
> +''
>
> /tmp/psr-http-message-bridge-dc7e308e1dc2898a46776e2221a643cb08315453/Tests/Factory/DiactorosFactoryTest.php:77

Perhaps `zendframework/zend-diactoros` could be added to require-dev so those tests would always be run?

My environment:
* Fedora 22
* PHP 5.6.10
* PHPUnit 4.7.4
* `symfony/symfony` 2.5.12
*  `zendframework/zend-diactoros` 1.1.2

**Comment by xabbuh** [comment]
Thank you for reporting this issue @siwinski. It will be fixed by symfony/symfony#15249.

**Comment by dunglas** [comment]
Btw `zendframework/zend-diactoros` is not in the `require-dev` section because it doesn't work with PHP 5.3 (but the Bridge does in the other way PSR-7 -> HttpFoundation). However, Diactoros tests are run by Travis: https://github.com/symfony/psr-http-message-bridge/blob/master/.travis.yml#L36

**Comment by siwinski** [comment]
THANKS @xabbuh 

@dunglas , ahhh, makes sense.  I didn't catch that nuance.  Thanks for the info.
