### ISSUE TITLE
Allow setting cookie values that will not be URL-encoded

### ISSUE THREAD

**Issue by charginghawk** [symfony/psr-http-message-bridge#83]
The HttpFoundation\Cookie class has been updated to support raw cookies:

https://github.com/symfony/symfony/issues/13646
https://github.com/symfony/symfony/pull/18105

But all cookies created through HttpFoundationFactory have "raw" set to false:

https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/HttpFoundationFactory.php#L221

Similar to the Symfony issue, I'm working with a 3rd party application that I need to have use the same cookie, but it can't because it doesn't expect the value to be URL-encoded. It'd be nice to have an option to not encode cookies.

**Comment by nicolas-grekas** [comment]
Since cookies are read from the Set-Cookie header, they're already url-encoded.
To me, this means that the `false` should be `true` in the first place.
Not need to make this configurable.

Would you mind sending a PR to fix this and add some test cases if you agree?
