### ISSUE TITLE
PsrHttpFactory::createResponse doesn't respect Content-Range headers from BinaryFileResponse

### ISSUE THREAD

**Issue by iluuu1994** [symfony/psr-http-message-bridge#84]
https://github.com/symfony/psr-http-message-bridge/blob/e44f249afab496b4e8c0f7461fb8140eaa4b24d2/Factory/PsrHttpFactory.php#L131-L133

When converting a `BinaryFileResponse` content to a PSR content the `Content-Range` header is ignored and the whole file is added to the response. The `Content-Range` header is still added to the converted response though which makes the response invalid. Replacing the code snippet with this fixes the issue:

```php
$stream = $this->streamFactory->createStreamFromFile('php://temp', 'wb+');
ob_start(function ($buffer) use ($stream) {
    $stream->write($buffer);
    return '';
});

$symfonyResponse->sendContent();
ob_end_clean();
```

This does mean the range has to be loaded fully into memory. There might be a better solution. Let me know if I should create a pull request.

**Comment by nicolas-grekas** [comment]
Please send a PR yes so we can discuss the proposal.

**Comment by iluuu1994** [comment]
Optimally, we'd only load the file into memory when a range is emitted. We could check for the presence of the `Content-Range` header but that wouldn't be accurate because you could set the file and headers independently (maybe the attached file is already a chunk of a larger file).

To accurately know if the file is chunked we'd need this method in `BinaryFileResponse`:

```php
public function sendsPartialStream(): bool
{
    return $this->maxlen !== -1 || $this->offset !== 0;
}
```

Since this package supports Symfony 4.4 it would have to be added there. I'm not sure if that's acceptable according to the Symfony BC guidelines. The alternative would be to ignore this edge case and just check for the `Content-Range` header. Let me know which approach seems better to you.
