### ISSUE TITLE
Bridge error when no file is selected

### ISSUE THREAD

**Issue by ahundiak** [symfony/psr-http-message-bridge#9]
The bridge throws an error when a file element is posted without selecting a file.

    $_FILES
    Array ( [file] => Array ( [name] => [type] => [tmp_name] => [error] => 4 [size] => 0 ) ) 
    error = 4 = UPLOAD_ERR_NO_FILE

    $symfonyRequest->files->all()
    Array ( [file] =>)

    Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory::getFiles()
    Catchable Fatal Error: Argument 1 passed to    
    Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory::getFiles() must be of the type array, 
    null given

The problem is that the Symfony request object contains a null for file elements if no file was selected.  One could argue that it should return an UploadedFile object with an error code of UPLOAD_ERR_NO_FILE (4) but obviously this is not something that would be considered for S2.7.  Don't know if it has been discussed for 3.x.

However, the PSR7 spec seems clear:

    interface ServerRequestInterface extends RequestInterface
    public function getUploadedFiles();
    * This method returns upload metadata in a normalized tree, with each leaf
    * an instance of Psr\Http\Message\UploadedFileInterface.

So for PSR7 we should return metadata even if a file was not actually uploaded.  Which is exactly what Zend\Diactoros\ServerRequestFactory::fromGlobals() does.

It's easy enough to update the bridge to match the Zend PSR7 behavior when no file has been selected.  I'll be glad to submit a pull request.  Just wanted to make sure that it would be accepted.

**Comment by stof** [comment]
returning ``null`` inside ``$symfonyRequest->files->all()`` looks like a bug to me. It does not respect the documented API (and even core developers of Symfony are getting caught by this bug, proved by this issue).

@fabpot I suggest fixing the bug in Symfony directly. I guess this is also the root cause for some other bug report we received on Symfony

**Comment by xabbuh** [comment]
@stof `all()` itself does return an array, but this array can contain `null` as an element whhich does not violate the interface.
